### ISSUE TITLE
function already exsits/ debug

### ISSUE THREAD

**Issue by dazu1990** [heliosdesign/helios-frame-runner#1]
We need some kind of debug toggle and a way of easily checking whether or not framerunner has a function assigned to it. I run into a frequent problem where I have a play/pause button for a scrub bar and on play I add a function to framerunner  and start it up. On pause I remove the function and then stop framerunner. Yet when I play again the function is still there. 

Frame runner already fails gracefully and sends a console log saying that the function already exsist which is fine but it become super annoying to have those console logs constantly firing. I understand that the playpause function itself should be checking a variable that is the player state before firing, but I still find that frame runner dosn't seem to remove functions reliably. It would be helpful to a have a function that returns a boolean stating whether or not that function exists. Something similar to "framerunner.get('myfunction'); ". This would be especially useful in projects that have multiple framerunner functions firing. 

There also needs to be some kind of shut off for the debugging logs that can be accessed through a global variable for when we release for production. So on the site we can use:

if( server !== 'localhost') {
framerunner.debug = false;
}

**Comment by iainmcampbell** [comment]
[see release v2](https://github.com/heliosdesign/helios-frame-runner/releases/tag/v2.0.0)
